services:
  app1:
    volumes:
      - .:/othello
    image: cosmtrek/air
    ports:
      - "4000:4000"
      - "3000:3000"
    environment:
      - air_wd=/othello

  app2:
    volumes:
      - .:/othello
    image: cosmtrek/air
    ports:
      - "4001:4000"
      - "3001:3000"
    environment:
      - air_wd=/othello
